name: Validate Pull Request
on:
  pull_request:


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 1
          labels: "breaking-change,enhancement,bug,chore,documentation"

      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform formatt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: "${{ github.workspace }}"

      - uses: terraform-docs/gh-actions@v1.0
        with:
          working-dir: "${{ github.workspace }}"
          git-push: "false"
          config-file: "${{ github.workspace }}/.config/.terraform-docs.yaml"
          fail-on-diff: "true"
